FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

RUN mkdir /usr/src/app -p && touch /usr/src/app/index.js

WORKDIR /usr/src/app

EXPOSE 8080:80

#CMD ["nginx", "-g", "daemon off;""]